# Generated by Django 4.0.5 on 2022-06-13 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
