# Generated by Django 4.0.5 on 2022-06-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_rename_firstname_player_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='updated_at',
        ),
    ]
