# Generated by Django 4.0.5 on 2022-06-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_rename_player_playerin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerIn',
            new_name='Player',
        ),
    ]
